### ISSUE TITLE
Add a PDF merger in JavaScript 

### ISSUE THREAD

**Issue by JohnArryn22** [JohnArryn22/MinorsInLanguages#1]
Feat: Can be able to merge multiple PDFs.

**Comment by AnushkJain2201** [comment]
Assign it to me.
@JohnArryn22

**Comment by JohnArryn22** [comment]
@AnushkJain2201  you are assigned. Raise a PR.

**Comment by AnushkJain2201** [comment]
I had raised a PR. Please review it and merge it @JohnArryn22

**Comment by JohnArryn22** [comment]
Merging it
